
program := item

item := object
item := string

items __EPSILON__
__CHAIN__ items := items item

object := type ( object-params )

object-params __EPSILON__
__CHAIN__ object-params := object-params object-param

object-param := item
object-param := name = item